import { useEffect, useRef, useState, type ReactNode } from 'react'
import { money, percent, recoveryMetrics, selectedRecoveryCase, useRecoveryData, type RecoveryAuditRecord } from '../lib/recovery'
import { useWorkspace } from '../store/workspace'
import type { ViewId } from '../lib/types'
import { Markdown } from '../components/Markdown'
import { activeConversation, deleteConversation, newConversation, regenerate, send, setAnalystContext, useChat } from '../lib/chat'

const title = (value: string) => value.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())
const statusClass = (value: string) => value.toLowerCase().replace(/\s+/g, '-')

function Badge({ value }: { value: string }) { return <span className={`omx-rev-badge ${statusClass(value)}`}>{title(value)}</span> }
function Page({ eyebrow, heading, children, action }: { eyebrow: string; heading: string; children: ReactNode; action?: ReactNode }) {
  return <div className="omx-scroll omx-rev-page"><div className="omx-rev-header"><div><div className="omx-rev-kicker">REVORA · {eyebrow}</div><h1>{heading}</h1><p>Simulated recovery benchmark · AI recommends, evidence verifies, policy authorizes.</p></div>{action}</div>{children}</div>
}
function DataGate({ children }: { children: (records: RecoveryAuditRecord[]) => ReactNode }) {
  const load = useRecoveryData((s) => s.load); const data = useRecoveryData((s) => s.data); const loading = useRecoveryData((s) => s.loading); const error = useRecoveryData((s) => s.error); const refresh = useRecoveryData((s) => s.refresh)
  useEffect(() => { void load() }, [load])
  if (loading && !data) return <div className="omx-rev-banner">Running recovery analysis…</div>
  if (error && !data) return <div className="omx-rev-banner warn">Unable to load recovery data. {error} <button className="omx-btn" onClick={() => void refresh()}>Retry</button></div>
  if (!data || !data.audit_trail.length) return <div className="omx-empty"><h3>No recovery cases in this benchmark</h3><p>Refresh after the recovery API has evaluated a batch.</p></div>
  return <>{error && <div className="omx-rev-banner warn">Showing the last loaded benchmark. {error}</div>}{children(data.audit_trail)}</>
}
function CaseLink({ record, label = 'View transaction', view = 'table' }: { record: RecoveryAuditRecord; label?: string; view?: ViewId }) {
  const setView = useWorkspace((s) => s.setView); const select = useRecoveryData((s) => s.selectCase)
  return <button className="omx-btn" onClick={() => { select(record.transaction_id); setView(view) }}>{label}</button>
}
function CaseSummary({ record }: { record: RecoveryAuditRecord | null }) {
  if (!record) return <div className="omx-empty"><h3>Select a recovery case</h3><p>Choose a transaction in Recovery Queue to inspect its decision path.</p></div>
  const fields: [string, string][] = [
    ['Transaction', record.transaction_id], ['Merchant', record.merchant_id], ['Amount', money(record.amount)], ['Payment method', record.payment_method], ['Failure', `${record.failure_type} · ${record.failure_code}`], ['Retry count', String(record.retry_count)], ['AI recommendation', title(record.recommended_action)], ['Evidence', `${title(record.evidence_verdict)} · ${percent(record.evidence_confidence)}`], ['Policy', `${record.allowed ? 'Authorized' : 'Manual review'} · ${record.policy_reason}`], ['Outcome', record.status], ['Recovered', money(record.amount_recovered)],
  ]
  return <div className="omx-rev-panel"><div className="omx-rev-case-head"><div><span className="omx-rev-kicker">Selected recovery case</span><h2>{record.transaction_id}</h2></div><Badge value={record.status} /></div><div className="omx-rev-detail-grid">{fields.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="omx-rev-rule"><strong>Execution record</strong><span>{record.attempted ? record.execution_message : 'No simulated execution occurred.'}</span></div></div>
}

export function RecoveryDashboardView() {
  const setView = useWorkspace((s) => s.setView); const select = useRecoveryData((s) => s.selectCase); const setQueueStatus = useRecoveryData((s) => s.setQueueStatus); const data = useRecoveryData((s) => s.data)
  return <Page eyebrow="Recovery dashboard" heading="Revenue recovery, under control"><DataGate>{(records) => { const m = recoveryMetrics(data!); const go = (view: ViewId, status?: string) => { if (status) setQueueStatus(status); setView(view) }; return <>
    <div className="omx-rev-grid four"><button className="omx-rev-stat" onClick={() => go('table')}><div className="omx-rev-stat-label">Revenue at risk</div><div className="omx-rev-stat-value">{money(m.revenueAtRisk)}</div><div className="omx-rev-stat-detail">{m.failedPayments} failed payments</div></button><button className="omx-rev-stat" onClick={() => go('table')}><div className="omx-rev-stat-label">Recovery opportunities</div><div className="omx-rev-stat-value">{m.baselineOpportunities}</div><div className="omx-rev-stat-detail">Detected in benchmark</div></button><button className="omx-rev-stat" onClick={() => go('table', 'approved')}><div className="omx-rev-stat-label">AI approved</div><div className="omx-rev-stat-value">{m.aiApproved}</div><div className="omx-rev-stat-detail">Policy-authorized candidates</div></button><button className="omx-rev-stat" onClick={() => go('table', 'recovered')}><div className="omx-rev-stat-label">Simulated revenue recovered</div><div className="omx-rev-stat-value">{money(m.aiRevenue)}</div><div className="omx-rev-stat-detail">{m.aiRecovered} successful outcomes</div></button></div>
    <div className="omx-rev-grid four" style={{ marginTop: 12 }}><button className="omx-rev-stat" onClick={() => go('table')}><div className="omx-rev-stat-label">AI candidates</div><div className="omx-rev-stat-value">{m.aiCandidates}</div></button><button className="omx-rev-stat" onClick={() => go('compare')}><div className="omx-rev-stat-label">Recovery rate</div><div className="omx-rev-stat-value">{percent(m.recoveryRate)}</div></button><button className="omx-rev-stat" onClick={() => setView('model-quality')}><div className="omx-rev-stat-label">False approvals</div><div className="omx-rev-stat-value">{m.falseApprovals}</div></button><button className="omx-rev-stat" onClick={() => setView('model-quality')}><div className="omx-rev-stat-label">Model quality</div><div className="omx-rev-stat-value">{percent(m.f1)}</div><div className="omx-rev-stat-detail">F1 benchmark score</div></button></div>
    <section className="omx-rev-panel" style={{ marginTop: 18 }}><h2>Controlled recovery pipeline</h2><div className="omx-rev-pipeline">{[['Detect', 'Failures identified'], ['AI diagnosis', 'Bounded recommendation'], ['Evidence verification', 'Context checked'], ['Policy authorization', 'Rules enforced'], ['Simulated recovery', 'Measured outcome'], ['Audit trail', 'Decision retained']].map(([a, b], i) => <button key={a} className="omx-rev-pipe-step" onClick={() => setView((['table','sources','claims','policies','timeline','audit'] as ViewId[])[i])}><b>{String(i + 1).padStart(2, '0')}</b><strong>{a}</strong><span>{b}</span></button>)}</div></section>
    <section className="omx-rev-panel" style={{ marginTop: 18 }}><h2>Recovery cases needing attention</h2><div className="omx-rev-list">{records.slice(0, 5).map((r) => <button key={r.transaction_id} onClick={() => { select(r.transaction_id); setView('table') }}><span>{r.transaction_id}</span><span>{r.merchant_id}</span><span>{money(r.amount)}</span><Badge value={r.status} /></button>)}</div></section>
  </>}}</DataGate></Page>
}

export function RecoveryQueueView() {
  const [query, setQuery] = useState(''); const [decision, setDecision] = useState('all'); const [method, setMethod] = useState('all'); const [sort, setSort] = useState<'amount' | 'confidence'>('amount'); const status = useRecoveryData((s) => s.queueStatus); const setStatus = useRecoveryData((s) => s.setQueueStatus); const select = useRecoveryData((s) => s.selectCase); const setView = useWorkspace((s) => s.setView)
  return <Page eyebrow="Recovery queue" heading="Transaction-level recovery workspace"><DataGate>{(records) => { const statuses = ['all', 'recovered', 'manual review', 'blocked', 'approved']; const methods = [...new Set(records.map((r) => r.payment_method))]; const rows = records.filter((r) => (!query || `${r.transaction_id} ${r.merchant_id} ${r.failure_code}`.toLowerCase().includes(query.toLowerCase())) && (status === 'all' || (status === 'approved' ? r.allowed : r.status.toLowerCase() === status)) && (decision === 'all' || (decision === 'authorized' ? r.allowed : !r.allowed)) && (method === 'all' || r.payment_method === method)).sort((a,b) => sort === 'amount' ? b.amount-a.amount : b.evidence_confidence-a.evidence_confidence); return <><div className="omx-rev-filters"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search transaction, merchant, failure…" />{statuses.map((s) => <button key={s} className={status === s ? 'on' : ''} onClick={() => setStatus(s)}>{title(s)}</button>)}<select value={decision} onChange={(e) => setDecision(e.target.value)}><option value="all">All decisions</option><option value="authorized">Authorized</option><option value="review">Manual review</option></select><select value={method} onChange={(e) => setMethod(e.target.value)}><option value="all">All payment methods</option>{methods.map((m) => <option key={m}>{m}</option>)}</select><button className="omx-btn" onClick={() => setSort(sort === 'amount' ? 'confidence' : 'amount')}>Sort: {title(sort)}</button></div><div className="omx-rev-panel omx-rev-table-wrap"><table className="omx-rev-table"><thead><tr>{['Transaction','Merchant','Amount','Payment method','Failure','AI action','Confidence','Policy','Status','Recovered'].map((h) => <th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r) => <tr key={r.transaction_id} onClick={() => { select(r.transaction_id); setView('sources') }}><td>{r.transaction_id}</td><td>{r.merchant_id}</td><td>{money(r.amount)}</td><td>{r.payment_method}</td><td>{r.failure_code}</td><td>{title(r.recommended_action)}</td><td>{percent(r.evidence_confidence)}</td><td><Badge value={r.allowed ? 'authorized' : 'manual review'} /></td><td><Badge value={r.status} /></td><td>{money(r.amount_recovered)}</td></tr>)}</tbody></table>{!rows.length && <div className="omx-empty"><h3>No cases match these filters</h3><p>Clear a filter to inspect the current benchmark.</p></div>}</div></> }}</DataGate></Page>
}

export function SelectedPage({ kind }: { kind: 'evidence' | 'context' | 'graph' | 'timeline' | 'audit' }) {
  const selected = useRecoveryData(selectedRecoveryCase); const setView = useWorkspace((s) => s.setView)
  const labels = { evidence: ['Evidence verification', 'Evidence supporting the selected recovery decision'], context: ['Payment context', 'Why this payment is at risk'], graph: ['Decision graph', 'The selected transaction’s actual recovery path'], timeline: ['Recovery timeline', 'Chronological recovery process'], audit: ['Audit trail', 'Financial operations record for the selected case'] } as const
  return <Page eyebrow={labels[kind][0]} heading={labels[kind][1]} action={<button className="omx-btn" onClick={() => setView('table')}>Browse recovery queue</button>}><DataGate>{() => <>{kind === 'graph' ? <DecisionGraph record={selected} /> : kind === 'timeline' ? <Timeline record={selected} /> : <CaseSummary record={selected} />}{kind === 'evidence' && selected && <section className="omx-rev-panel"><h2>Evidence verdict</h2><p>{title(selected.evidence_verdict)} evidence at {percent(selected.evidence_confidence)} confidence. Policy outcome: {selected.allowed ? 'authorized for bounded simulated action' : 'manual review required'}.</p><CaseLink record={selected} /></section>}{kind === 'audit' && selected && <section className="omx-rev-panel"><h2>Rules checked</h2><div className="omx-rev-chips">{selected.rules_checked.map((r) => <span key={r}>{title(r)}</span>)}</div><p><strong>Authorization:</strong> {selected.policy_action} — {selected.policy_reason}</p><p><strong>Execution:</strong> {selected.attempted ? selected.execution_message : 'Not executed; case stopped before simulated recovery.'}</p></section>}</>}</DataGate></Page>
}
function DecisionGraph({ record }: { record: RecoveryAuditRecord | null }) { const [open, setOpen] = useState(0); if (!record) return <CaseSummary record={record} />; const steps = [['Payment failed', `${record.failure_type} · ${record.failure_code}`], ['Recovery candidate', title(record.recommended_action)], ['AI diagnosis', `${percent(record.evidence_confidence)} confidence`], ['Evidence verification', title(record.evidence_verdict)], ['Policy authorization', record.allowed ? 'Authorized' : `Manual review: ${record.policy_reason}`], ['Simulated outcome', record.success ? `Recovered ${money(record.amount_recovered)}` : record.execution_message]]; return <div className="omx-rev-panel"><div className="omx-rev-graph">{steps.map(([label, detail], i) => <button className={open === i ? 'on' : ''} onClick={() => setOpen(i)} key={label}><b>{label}</b><span>{detail}</span></button>)}</div><div className="omx-rev-rule"><strong>{steps[open][0]}</strong><span>{steps[open][1]}</span></div></div> }
function Timeline({ record }: { record: RecoveryAuditRecord | null }) { if (!record) return <CaseSummary record={record} />; const steps = [['Detection', `Failure ${record.failure_code} identified`], ['Diagnosis', `${title(record.recommended_action)} recommended`], ['Evidence', `${title(record.evidence_verdict)} at ${percent(record.evidence_confidence)}`], ['Authorization', record.allowed ? 'Policy authorized bounded action' : record.policy_reason], ['Execution', record.attempted ? record.execution_message : 'No simulated execution'], ['Outcome', `${record.status} · ${money(record.amount_recovered)}`]]; return <section className="omx-rev-panel omx-rev-timeline">{steps.map(([a,b], i) => <div key={a}><b>{String(i+1).padStart(2,'0')}</b><strong>{a}</strong><span>{b}</span></div>)}</section> }

export function RecoveryBriefView() { const data = useRecoveryData((s) => s.data); return <Page eyebrow="Recovery brief" heading="Current benchmark operational summary"><DataGate>{(records) => { const m = recoveryMetrics(data!); const byFailure = Object.entries(records.reduce<Record<string, number>>((a,r) => { a[r.failure_type] = (a[r.failure_type] ?? 0) + 1; return a }, {})); return <div className="omx-rev-brief"><section><h2>Executive summary</h2><p>{money(m.revenueAtRisk)} is at risk across {m.failedPayments} failed payments. Revora found {m.aiCandidates} AI candidates, authorized {m.aiApproved}, and simulated {money(m.aiRevenue)} recovered revenue at a {percent(m.recoveryRate)} recovery rate.</p></section><section><h2>What Revora found</h2><p>Most common failure patterns: {byFailure.map(([k,v]) => `${title(k)} (${v})`).join(', ') || 'No failure categories returned'}.</p><p>{records.filter(r => r.allowed).length} cases passed policy controls; {records.filter(r => !r.allowed).length} were stopped or routed to manual review.</p></section><section><h2>Control & governance</h2><p>Minimum confidence 80% · maximum retry count 2 · Maximum Automatic Amount ₹50,000. Unsupported actions, failed evidence, low confidence, and exhausted retries require manual review.</p></section><section><h2>Outcome</h2><p>{m.aiRecovered} successful simulated recoveries; {records.filter(r => r.status !== 'Recovered').length} blocked or manual-review cases. No real payment execution is represented.</p></section></div>}}</DataGate></Page> }
export function RecoveryMonitorsView() { const data = useRecoveryData(s=>s.data); const refresh = useRecoveryData(s=>s.refresh); return <Page eyebrow="Recovery monitors" heading="Current recovery batch monitoring" action={<button className="omx-btn primary" onClick={() => void refresh()}>Refresh benchmark</button>}><DataGate>{(records) => { const m = recoveryMetrics(data!); return <><div className="omx-rev-banner">This is a frontend representation of the current benchmark run, not persistent production monitoring.</div><div className="omx-rev-grid four"><Stat label="Batch status" value={data!.status} /><Stat label="Failed payments" value={String(m.failedPayments)} /><Stat label="Opportunities" value={String(m.baselineOpportunities)} /><Stat label="AI candidates" value={String(m.aiCandidates)} /><Stat label="Approved" value={String(m.aiApproved)} /><Stat label="Recovered revenue" value={money(m.aiRevenue)} /><Stat label="Manual / blocked" value={String(records.filter(r=>r.status !== 'Recovered').length)} /></div></>}}</DataGate></Page> }
function Stat({ label, value }: { label:string; value:string }) { return <div className="omx-rev-stat"><div className="omx-rev-stat-label">{label}</div><div className="omx-rev-stat-value">{value}</div></div> }
export function RecoveryReportsView() { const data=useRecoveryData(s=>s.data); const refresh=useRecoveryData(s=>s.refresh); const setView=useWorkspace(s=>s.setView); return <Page eyebrow="Recovery reports" heading="Current recovery run report" action={<><button className="omx-btn" onClick={() => setView('table')}>View cases</button><button className="omx-btn primary" onClick={() => void refresh()}>Refresh data</button></>}><DataGate>{(records)=>{const m=recoveryMetrics(data!);return <div className="omx-rev-brief"><section><h2>Recovery performance</h2><p>{money(m.aiRevenue)} simulated recovered revenue from {m.aiRecovered} successful cases. Revenue at risk: {money(m.revenueAtRisk)}.</p></section><section><h2>AI and policy outcomes</h2><p>{m.aiCandidates} candidates · {m.aiApproved} authorized · {records.filter(r=>!r.allowed).length} routed to manual review · {m.falseApprovals} false approvals.</p></section><section><h2>Audit statistics</h2><p>{records.filter(r=>r.attempted).length} simulated actions attempted. Every case has a policy result and execution outcome in the Audit Trail.</p></section></div>}}</DataGate></Page> }
export function RecoveryAgentsView() { return <Page eyebrow="Recovery agents" heading="Bounded recovery agent architecture"><div className="omx-rev-panel"><div className="omx-rev-pipeline">{[['Detector','Identifies failed payments'],['AI diagnosis','Recommends an action'],['Evidence verification','Checks transaction context'],['Policy engine','Authorizes deterministic bounds'],['Executor','Performs only bounded simulated recovery'],['Measurement','Calculates outcomes'],['Audit trail','Retains decision evidence']].map(([a,b])=><div className="omx-rev-pipe-step" key={a}><strong>{a}</strong><span>{b}</span></div>)}</div><p className="omx-rev-sub">AI recommends. Evidence verifies. Policy authorizes. The executor does not give an LLM control of payment execution.</p></div></Page> }
export function RecoveryAnalyticsPage() { const data=useRecoveryData(s=>s.data); return <Page eyebrow="Recovery analytics" heading="Recovery performance from the current dataset"><DataGate>{(records)=>{const m=recoveryMetrics(data!); const groups = (key: keyof RecoveryAuditRecord) => Object.entries(records.reduce<Record<string,{total:number,recovered:number}>>((a,r)=>{const k=String(r[key]); const x=a[k]??{total:0,recovered:0};x.total++;if(r.success)x.recovered++;a[k]=x;return a},{}));return <><div className="omx-rev-grid four"><Stat label="Recovery rate" value={percent(m.recoveryRate)} /><Stat label="Baseline recovery" value={money(m.baselineRevenue)} /><Stat label="AI incremental recovery" value={money(m.aiRevenue)} /><Stat label="AI approval rate" value={percent(m.aiCandidates ? m.aiApproved/m.aiCandidates : 0)} /></div><section className="omx-rev-panel"><h2>Outcomes by failure type</h2><MetricRows entries={groups('failure_type')} /></section><section className="omx-rev-panel"><h2>Outcomes by payment method</h2><MetricRows entries={groups('payment_method')} /></section></>}}</DataGate></Page> }
function MetricRows({ entries }: { entries: [string,{total:number;recovered:number}][] }) { return <div className="omx-rev-list">{entries.map(([label,v])=><div key={label}><span>{title(label)}</span><span>{v.recovered} / {v.total} recovered</span><span>{percent(v.total ? v.recovered/v.total : 0)}</span></div>)}</div> }
export function PoliciesPage() { return <Page eyebrow="Policies" heading="Current active recovery policy"><div className="omx-rev-panel"><h2>Current active policy</h2><div className="omx-rev-detail-grid"><div><span>Minimum confidence</span><strong>0.80</strong></div><div><span>Maximum retry count</span><strong>2</strong></div><div><span>Maximum Automatic Amount</span><strong>₹50,000</strong></div><div><span>Automated action</span><strong>retry_payment</strong></div></div><h2 style={{marginTop:20}}>Stopping rules</h2><div className="omx-rev-chips">{['Unsupported actions → manual review','Failed evidence verification → manual review','Low confidence → manual review','Retry limit reached → manual review'].map(x=><span key={x}>{x}</span>)}</div><p className="omx-rev-sub">These values reflect backend policy configuration. Controls are informational until backend configuration support exists.</p></div></Page> }
export function ModelQualityPage() { const data=useRecoveryData(s=>s.data); return <Page eyebrow="Model quality" heading="Benchmark quality and decision safety"><DataGate>{()=>{const m=recoveryMetrics(data!);return <><div className="omx-rev-grid four"><Stat label="Precision" value={percent(m.precision)} /><Stat label="Recall" value={percent(m.aiRecall)} /><Stat label="F1" value={percent(m.f1)} /><Stat label="False approvals" value={String(m.falseApprovals)} /><Stat label="AI approved" value={String(m.aiApproved)} /><Stat label="Successful AI recoveries" value={String(m.aiRecovered)} /></div><section className="omx-rev-panel"><h2>How to read this</h2><p>Precision is the share of approved cases that successfully recovered. Recall is the share of ground-truth recoverable cases captured by AI. A lower recall can reflect intentionally conservative candidate evaluation and policy gates; it is not hidden or treated as a production guarantee.</p></section></>}}</DataGate></Page> }
const ASK_SUGGESTIONS = ['Why is revenue at risk?', 'Which failed payments are best candidates for recovery?', 'Why was this transaction sent to manual review?', 'Explain the recovery policy.', 'Compare baseline recovery with AI-assisted recovery.', 'What are the model precision and recall?']

export function AskRevoraPage() {
  const data = useRecoveryData((s) => s.data)
  const selected = useRecoveryData(selectedRecoveryCase)
  const { busy } = useChat()
  const conversation = activeConversation()
  const [draft, setDraft] = useState('')
  const endRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!data) { setAnalystContext(''); return }
    const metrics = recoveryMetrics(data)
    const caseContext = selected ? `\nSelected recovery case:\n${JSON.stringify(selected)}` : '\nNo transaction is currently selected.'
    setAnalystContext(`You are Revora, an AI-assisted revenue recovery analyst. Analyze only the supplied simulated recovery benchmark. Never claim a real customer payment was charged, retried, or recovered. Clearly distinguish AI recommendation, evidence verification, policy authorization, and simulated execution. If a requested fact is absent, say so.\n\nCurrent benchmark metrics:\n${JSON.stringify(metrics)}\n\nActive policy: minimum confidence 0.80; maximum retry count 2; Maximum Automatic Amount ₹50,000; automated action retry_payment. Unsupported actions, failed evidence, low confidence, and exhausted retries require manual review.${caseContext}`)
  }, [data, selected])
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: 'smooth', block: 'end' }) }, [conversation.messages.length, busy])

  const submit = async () => { const text = draft.trim(); if (!text || busy) return; setDraft(''); await send(text) }
  return <Page eyebrow="Ask Revora" heading="AI revenue recovery analyst" action={<><button className="omx-btn" onClick={() => deleteConversation(conversation.id)}>Clear conversation</button><button className="omx-btn" onClick={() => newConversation()}>New conversation</button></>}><DataGate>{() => <div className="omx-rev-chat"><div className="omx-rev-chat-history">{conversation.messages.length === 0 ? <div className="omx-empty"><h3>Ask about the active recovery benchmark</h3><p>{selected ? `Selected case: ${selected.transaction_id}. Your questions will include its current recovery record.` : 'Select a case in Recovery Queue for transaction-specific analysis.'}</p><div className="omx-rev-chips">{ASK_SUGGESTIONS.map((q) => <button key={q} onClick={() => setDraft(q)}>{q}</button>)}</div></div> : conversation.messages.map((message) => <div className={`omx-rev-chat-turn ${message.role}`} key={message.id}><div className="omx-label">{message.role === 'user' ? 'YOU' : 'REVORA'} {message.model ? `· ${message.model}` : ''}</div>{message.role === 'assistant' ? <Markdown className="omx-turn-body" text={message.text} /> : <p>{message.text}</p>}{message.error && <div className="omx-rev-banner warn">{message.error} <button className="omx-btn" onClick={() => void regenerate(message.id)}>Retry</button></div>}{message.sources?.length ? <div className="omx-rev-chips">{message.sources.map((source) => <a key={source.n} href={source.url} target="_blank" rel="noreferrer">{source.n}. {source.title || source.url}</a>)}</div> : null}</div>)}{busy && <div className="omx-rev-chat-turn assistant"><div className="omx-label">REVORA</div><span className="omx-spin" /> <span className="omx-label">Analyzing the recovery benchmark…</span></div>}<div ref={endRef} /></div><div className="omx-rev-chat-compose"><textarea value={draft} rows={3} disabled={busy} placeholder={selected ? `Ask about ${selected.transaction_id} or the current benchmark…` : 'Ask about the current recovery benchmark…'} onChange={(event) => setDraft(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); void submit() } }} /><button className="omx-btn primary" onClick={() => void submit()} disabled={busy || !draft.trim()}>{busy ? <span className="omx-spin" /> : 'Send'}</button></div></div>}</DataGate></Page>
}
