"""baseline schema

Revision ID: 3952abef8d22
Revises: 
Create Date: 2026-08-03 12:43:14.293041
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '3952abef8d22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_call',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('execution_id', sa.String(length=32), nullable=True),
    sa.Column('step_id', sa.String(length=32), nullable=True),
    sa.Column('agent', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('capability', sa.String(length=32), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('tokens_estimated', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('ttft_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_call', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_call_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_call_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_call_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_call_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_modelcall_ws_ts', ['workspace_id', 'ts'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('workspace',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('settings_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_user_id'), ['user_id'], unique=False)

    op.create_table('artifact',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source_agent', sa.String(length=32), nullable=False),
    sa.Column('execution_id', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('tags_json', sa.JSON(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_artifact_ws_created', ['workspace_id', 'created_at'], unique=False)

    op.create_table('claim',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('execution_id', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('verdict', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('supported_by_json', sa.JSON(), nullable=False),
    sa.Column('contradicted_by_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('execution',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('agent', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('plan_json', sa.JSON(), nullable=False),
    sa.Column('parent_execution_id', sa.String(length=32), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_agent'), ['agent'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_parent_execution_id'), ['parent_execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_execution_ws_created', ['workspace_id', 'created_at'], unique=False)

    op.create_table('finding',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('execution_id', sa.String(length=32), nullable=False),
    sa.Column('rule_id', sa.String(length=80), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('location_json', sa.JSON(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('impact', sa.Text(), nullable=False),
    sa.Column('remediation', sa.Text(), nullable=False),
    sa.Column('references_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('fixed_by_execution_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('memory_item',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('source_execution_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_item_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('object',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('external_id', sa.String(length=300), nullable=False),
    sa.Column('properties_json', sa.JSON(), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('salience', sa.Float(), nullable=False),
    sa.Column('tracked', sa.Boolean(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('execution_id', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('object', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_object_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_object_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_object_provenance'), ['provenance'], unique=False)
        batch_op.create_index(batch_op.f('ix_object_tracked'), ['tracked'], unique=False)
        batch_op.create_index(batch_op.f('ix_object_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_object_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_object_ws_ext', ['workspace_id', 'external_id'], unique=False)
        batch_op.create_index('ix_object_ws_type', ['workspace_id', 'type'], unique=False)

    op.create_table('repo',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=False),
    sa.Column('default_branch', sa.String(length=120), nullable=False),
    sa.Column('map_json', sa.JSON(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repo_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('saved_view',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('view', sa.String(length=32), nullable=False),
    sa.Column('state_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_view', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_view_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('source',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('execution_id', sa.String(length=32), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('publisher', sa.String(length=200), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('tier_label', sa.String(length=80), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('credibility', sa.Integer(), nullable=False),
    sa.Column('duplicate_of', sa.String(length=32), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('depends_on_json', sa.JSON(), nullable=False),
    sa.Column('effort', sa.String(length=32), nullable=False),
    sa.Column('risk', sa.Text(), nullable=False),
    sa.Column('order_idx', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('usage_counter',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('metric', sa.String(length=48), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_counter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_counter_metric'), ['metric'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_counter_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_counter_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_usage_unique', ['workspace_id', 'period', 'metric'], unique=True)

    op.create_table('artifact_ref',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('from_artifact_id', sa.String(length=32), nullable=False),
    sa.Column('to_artifact_id', sa.String(length=32), nullable=False),
    sa.Column('relation', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_artifact_id'], ['artifact.id'], ),
    sa.ForeignKeyConstraint(['to_artifact_id'], ['artifact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifact_ref', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_ref_from_artifact_id'), ['from_artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_ref_to_artifact_id'), ['to_artifact_id'], unique=False)

    op.create_table('event',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('execution_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['execution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index('ix_event_exec_seq', ['execution_id', 'seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('execution_step',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('execution_id', sa.String(length=32), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('agent', sa.String(length=32), nullable=False),
    sa.Column('capability', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('depends_on_json', sa.JSON(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['execution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution_step', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_step_execution_id'), ['execution_id'], unique=False)

    op.create_table('object_event',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('object_id', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('relevance', sa.String(length=16), nullable=False),
    sa.Column('provenance', sa.String(length=24), nullable=False),
    sa.Column('properties_json', sa.JSON(), nullable=False),
    sa.Column('execution_id', sa.String(length=32), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['object.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('object_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_object_event_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_object_event_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_object_event_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_object_event_relevance'), ['relevance'], unique=False)
        batch_op.create_index(batch_op.f('ix_object_event_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_object_event_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_objevent_ws_occurred', ['workspace_id', 'occurred_at'], unique=False)

    op.create_table('relationship',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('src_id', sa.String(length=32), nullable=False),
    sa.Column('dst_id', sa.String(length=32), nullable=False),
    sa.Column('relation', sa.String(length=48), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('observations', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.Float(), nullable=False),
    sa.Column('provenance', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('properties_json', sa.JSON(), nullable=False),
    sa.Column('execution_id', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dst_id'], ['object.id'], ),
    sa.ForeignKeyConstraint(['src_id'], ['object.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relationship', schema=None) as batch_op:
        batch_op.create_index('ix_rel_unique', ['workspace_id', 'src_id', 'dst_id', 'relation'], unique=True)
        batch_op.create_index('ix_rel_ws_dst', ['workspace_id', 'dst_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationship_dst_id'), ['dst_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationship_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationship_provenance'), ['provenance'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationship_relation'), ['relation'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationship_src_id'), ['src_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationship_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('object_source',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('object_id', sa.String(length=32), nullable=True),
    sa.Column('relationship_id', sa.String(length=32), nullable=True),
    sa.Column('event_id', sa.String(length=32), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['object_event.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['object.id'], ),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationship.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('object_source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_object_source_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_object_source_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_object_source_relationship_id'), ['relationship_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_object_source_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_object_source_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('object_source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_object_source_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_object_source_source_id'))
        batch_op.drop_index(batch_op.f('ix_object_source_relationship_id'))
        batch_op.drop_index(batch_op.f('ix_object_source_object_id'))
        batch_op.drop_index(batch_op.f('ix_object_source_event_id'))

    op.drop_table('object_source')
    with op.batch_alter_table('relationship', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationship_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_relationship_src_id'))
        batch_op.drop_index(batch_op.f('ix_relationship_relation'))
        batch_op.drop_index(batch_op.f('ix_relationship_provenance'))
        batch_op.drop_index(batch_op.f('ix_relationship_execution_id'))
        batch_op.drop_index(batch_op.f('ix_relationship_dst_id'))
        batch_op.drop_index('ix_rel_ws_dst')
        batch_op.drop_index('ix_rel_unique')

    op.drop_table('relationship')
    with op.batch_alter_table('object_event', schema=None) as batch_op:
        batch_op.drop_index('ix_objevent_ws_occurred')
        batch_op.drop_index(batch_op.f('ix_object_event_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_object_event_type'))
        batch_op.drop_index(batch_op.f('ix_object_event_relevance'))
        batch_op.drop_index(batch_op.f('ix_object_event_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_object_event_object_id'))
        batch_op.drop_index(batch_op.f('ix_object_event_execution_id'))

    op.drop_table('object_event')
    with op.batch_alter_table('execution_step', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_step_execution_id'))

    op.drop_table('execution_step')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_event_type'))
        batch_op.drop_index(batch_op.f('ix_event_execution_id'))
        batch_op.drop_index('ix_event_exec_seq')

    op.drop_table('event')
    with op.batch_alter_table('artifact_ref', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_ref_to_artifact_id'))
        batch_op.drop_index(batch_op.f('ix_artifact_ref_from_artifact_id'))

    op.drop_table('artifact_ref')
    with op.batch_alter_table('usage_counter', schema=None) as batch_op:
        batch_op.drop_index('ix_usage_unique')
        batch_op.drop_index(batch_op.f('ix_usage_counter_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_usage_counter_period'))
        batch_op.drop_index(batch_op.f('ix_usage_counter_metric'))

    op.drop_table('usage_counter')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_workspace_id'))

    op.drop_table('task')
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_source_execution_id'))
        batch_op.drop_index(batch_op.f('ix_source_content_hash'))

    op.drop_table('source')
    with op.batch_alter_table('saved_view', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_view_workspace_id'))

    op.drop_table('saved_view')
    with op.batch_alter_table('repo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repo_workspace_id'))

    op.drop_table('repo')
    with op.batch_alter_table('object', schema=None) as batch_op:
        batch_op.drop_index('ix_object_ws_type')
        batch_op.drop_index('ix_object_ws_ext')
        batch_op.drop_index(batch_op.f('ix_object_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_object_type'))
        batch_op.drop_index(batch_op.f('ix_object_tracked'))
        batch_op.drop_index(batch_op.f('ix_object_provenance'))
        batch_op.drop_index(batch_op.f('ix_object_external_id'))
        batch_op.drop_index(batch_op.f('ix_object_execution_id'))

    op.drop_table('object')
    with op.batch_alter_table('memory_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_item_workspace_id'))

    op.drop_table('memory_item')
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_finding_rule_id'))
        batch_op.drop_index(batch_op.f('ix_finding_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_finding_execution_id'))

    op.drop_table('finding')
    with op.batch_alter_table('execution', schema=None) as batch_op:
        batch_op.drop_index('ix_execution_ws_created')
        batch_op.drop_index(batch_op.f('ix_execution_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_execution_status'))
        batch_op.drop_index(batch_op.f('ix_execution_parent_execution_id'))
        batch_op.drop_index(batch_op.f('ix_execution_agent'))

    op.drop_table('execution')
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_claim_execution_id'))

    op.drop_table('claim')
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.drop_index('ix_artifact_ws_created')
        batch_op.drop_index(batch_op.f('ix_artifact_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_artifact_type'))
        batch_op.drop_index(batch_op.f('ix_artifact_execution_id'))

    op.drop_table('artifact')
    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_user_id'))

    op.drop_table('workspace')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('model_call', schema=None) as batch_op:
        batch_op.drop_index('ix_modelcall_ws_ts')
        batch_op.drop_index(batch_op.f('ix_model_call_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_model_call_ts'))
        batch_op.drop_index(batch_op.f('ix_model_call_model'))
        batch_op.drop_index(batch_op.f('ix_model_call_execution_id'))

    op.drop_table('model_call')
    # ### end Alembic commands ###
