"""terra geospatial tables

Revision ID: 54e9d58d762a
Revises: 6cee58327cdc
Create Date: 2026-08-12 20:10:32.581946
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '54e9d58d762a'
down_revision = '6cee58327cdc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_cache',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('stored_at', sa.Float(), nullable=False),
    sa.Column('ttl_s', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('geo_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geo_cache_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_geo_cache_stored_at'), ['stored_at'], unique=False)

    op.create_table('geo_place',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=False),
    sa.Column('meta_json', sa.JSON(), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('last_visit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('geo_place', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geo_place_lat'), ['lat'], unique=False)
        batch_op.create_index(batch_op.f('ix_geo_place_lon'), ['lon'], unique=False)
        batch_op.create_index(batch_op.f('ix_geo_place_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_geo_place_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_geoplace_bbox', ['workspace_id', 'lat', 'lon'], unique=False)
        batch_op.create_index('ix_geoplace_ws_slug', ['workspace_id', 'slug'], unique=True)

    op.create_table('geo_preference',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('observations', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('geo_preference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geo_preference_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_geo_preference_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_geopref_unique', ['workspace_id', 'key'], unique=True)

    op.create_table('geo_route',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=False),
    sa.Column('origin_lon', sa.Float(), nullable=False),
    sa.Column('dest_lat', sa.Float(), nullable=False),
    sa.Column('dest_lon', sa.Float(), nullable=False),
    sa.Column('origin_label', sa.Text(), nullable=False),
    sa.Column('dest_label', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('alternatives', sa.Integer(), nullable=False),
    sa.Column('chosen_index', sa.Integer(), nullable=True),
    sa.Column('factors_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('geo_route', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geo_route_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_geo_route_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('geo_visit',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('place_id', sa.String(length=32), nullable=True),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('departed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dwell_s', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('geo_visit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geo_visit_arrived_at'), ['arrived_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_geo_visit_lat'), ['lat'], unique=False)
        batch_op.create_index(batch_op.f('ix_geo_visit_lon'), ['lon'], unique=False)
        batch_op.create_index(batch_op.f('ix_geo_visit_place_id'), ['place_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_geo_visit_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_geovisit_ws_time', ['workspace_id', 'arrived_at'], unique=False)

    op.create_table('geofence',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('shape', sa.String(length=16), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('radius_m', sa.Float(), nullable=False),
    sa.Column('polygon_json', sa.JSON(), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('action_payload_json', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('inside', sa.Boolean(), nullable=False),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('geofence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geofence_lat'), ['lat'], unique=False)
        batch_op.create_index(batch_op.f('ix_geofence_lon'), ['lon'], unique=False)
        batch_op.create_index(batch_op.f('ix_geofence_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('geofence_event',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('geofence_id', sa.String(length=32), nullable=False),
    sa.Column('transition', sa.String(length=16), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('dispatched', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('geofence_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geofence_event_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_geofence_event_geofence_id'), ['geofence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_geofence_event_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geofence_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geofence_event_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_geofence_event_geofence_id'))
        batch_op.drop_index(batch_op.f('ix_geofence_event_created_at'))

    op.drop_table('geofence_event')
    with op.batch_alter_table('geofence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geofence_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_geofence_lon'))
        batch_op.drop_index(batch_op.f('ix_geofence_lat'))

    op.drop_table('geofence')
    with op.batch_alter_table('geo_visit', schema=None) as batch_op:
        batch_op.drop_index('ix_geovisit_ws_time')
        batch_op.drop_index(batch_op.f('ix_geo_visit_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_geo_visit_place_id'))
        batch_op.drop_index(batch_op.f('ix_geo_visit_lon'))
        batch_op.drop_index(batch_op.f('ix_geo_visit_lat'))
        batch_op.drop_index(batch_op.f('ix_geo_visit_arrived_at'))

    op.drop_table('geo_visit')
    with op.batch_alter_table('geo_route', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geo_route_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_geo_route_created_at'))

    op.drop_table('geo_route')
    with op.batch_alter_table('geo_preference', schema=None) as batch_op:
        batch_op.drop_index('ix_geopref_unique')
        batch_op.drop_index(batch_op.f('ix_geo_preference_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_geo_preference_key'))

    op.drop_table('geo_preference')
    with op.batch_alter_table('geo_place', schema=None) as batch_op:
        batch_op.drop_index('ix_geoplace_ws_slug')
        batch_op.drop_index('ix_geoplace_bbox')
        batch_op.drop_index(batch_op.f('ix_geo_place_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_geo_place_slug'))
        batch_op.drop_index(batch_op.f('ix_geo_place_lon'))
        batch_op.drop_index(batch_op.f('ix_geo_place_lat'))

    op.drop_table('geo_place')
    with op.batch_alter_table('geo_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geo_cache_stored_at'))
        batch_op.drop_index(batch_op.f('ix_geo_cache_kind'))

    op.drop_table('geo_cache')
    # ### end Alembic commands ###
