"""intents

Revision ID: 6cee58327cdc
Revises: abbcf408a9cf
Create Date: 2026-08-04 19:05:30.632700
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '6cee58327cdc'
down_revision = 'abbcf408a9cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intent',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('object_ids_json', sa.JSON(), nullable=False),
    sa.Column('keywords_json', sa.JSON(), nullable=False),
    sa.Column('relevance_floor', sa.String(length=16), nullable=False),
    sa.Column('cadence_minutes', sa.Integer(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_hit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intent_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_intent_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_intent_ws_status', ['workspace_id', 'status'], unique=False)

    op.create_table('intent_hit',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('intent_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('ref_id', sa.String(length=32), nullable=False),
    sa.Column('object_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('relevance', sa.String(length=16), nullable=False),
    sa.Column('matched_json', sa.JSON(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intent_id'], ['intent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intent_hit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intent_hit_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_intent_hit_intent_id'), ['intent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intent_hit_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intent_hit_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_intenthit_unique', ['intent_id', 'kind', 'ref_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intent_hit', schema=None) as batch_op:
        batch_op.drop_index('ix_intenthit_unique')
        batch_op.drop_index(batch_op.f('ix_intent_hit_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_intent_hit_object_id'))
        batch_op.drop_index(batch_op.f('ix_intent_hit_intent_id'))
        batch_op.drop_index(batch_op.f('ix_intent_hit_created_at'))

    op.drop_table('intent_hit')
    with op.batch_alter_table('intent', schema=None) as batch_op:
        batch_op.drop_index('ix_intent_ws_status')
        batch_op.drop_index(batch_op.f('ix_intent_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_intent_status'))

    op.drop_table('intent')
    # ### end Alembic commands ###
