"""conversation_turn

Revision ID: 81abef4e8474
Revises: 3952abef8d22
Create Date: 2026-08-04 00:22:58.872962
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '81abef4e8474'
down_revision = '3952abef8d22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_turn',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('execution_id', sa.String(length=32), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_turn', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_turn_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_turn_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_turn', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_turn_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_turn_created_at'))

    op.drop_table('conversation_turn')
    # ### end Alembic commands ###
