"""conversation_turn_seq

Revision ID: abbcf408a9cf
Revises: 81abef4e8474
Create Date: 2026-08-04 00:32:00.872682
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'abbcf408a9cf'
down_revision = '81abef4e8474'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # `server_default` is required, not cosmetic: SQLite refuses to add a NOT
    # NULL column to a populated table without one ("Cannot add a NOT NULL
    # column with default value NULL"), and the autogenerated version failed
    # against a live database for exactly that reason.
    with op.batch_alter_table('conversation_turn', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('seq', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_conversation_turn_seq'), ['seq'],
                              unique=False)

    # Backfill any turns written before this column existed. Ordering by
    # created_at is the best available signal for pre-existing rows; from here
    # on `seq` is assigned at insert and is authoritative.
    op.execute("""
        UPDATE conversation_turn
           SET seq = (
               SELECT COUNT(*) FROM conversation_turn AS t
                WHERE t.workspace_id = conversation_turn.workspace_id
                  AND (t.created_at < conversation_turn.created_at
                       OR (t.created_at = conversation_turn.created_at
                           AND t.id <= conversation_turn.id))
           )
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_turn', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_turn_seq'))
        batch_op.drop_column('seq')

    # ### end Alembic commands ###
